/***************************************************************
 * Name:      wxSmartHomeServerMain.h
 * Purpose:   Defines Application wxWidgets Frame class and
 *            GUI elements for project Linux "gateway" node
 * Author:    Bill Toner (wtoner1@jhu.edu)
 * Created:   2015-11-17
 * Copyright: Bill Toner (2015)
 * License:   This library is free software; you can redistribute it and/or
 *            modify it under the terms of the GNU Lesser General Public
 *            License as published by the Free Software Foundation; either
 *            version 2.1 of the License, or (at your option) any later version.
 *            http://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html
 *
 * Initially generated by wxSmith GUI builder tool
 **************************************************************/

#ifndef WXSMARTHOMESERVERMAIN_H
#define WXSMARTHOMESERVERMAIN_H


//(*Headers(wxSmartHomeServerFrame)
#include <wx/gauge.h>
#include <wx/bmpbuttn.h>
#include <wx/checkbox.h>
#include <wx/sizer.h>
#include <wx/menu.h>
#include <wx/panel.h>
#include <wx/statusbr.h>
#include <wx/statline.h>
#include <wx/frame.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/statbmp.h>
#include <wx/log.h>
#include <wx/file.h>
//*)


#include <stdint.h>

#include "SmartHomeServerAppDetails.h"

#include "SmartHome_Zigbee_Linux.h"
#include "SmartHome_NodeInfo.h"

#include "shLinuxSerialPort.h"


class wxSmartHomeServerFrame: public wxFrame
{
    public:
        uint16_t    shThisNodeID = 0;
//        wxString    SHconfigPath = defaultSHconfigPath;
        wxString    shPathConfig;
        wxString    shPathRooms;

        wxTextCtrl* shTextCtrlEvtlog;
        wxTextCtrl* shTextCtrlCurrentDate;
        wxTextCtrl* shTextCtrlCurrentTime;
        wxGauge*    shIntensityGauge;
        uint8_t     shGetNewLoadCurIntensity = NO; // flag indicates if need to ask load via Zigbee for its current intensity

        //#define SH_DEBUG_LOG_FILENAME  "/home/billt/shDebugLog.log"
        const wxString SH_DEBUG_LOG_FILENAME  = "/home/billt/shDebugLog.log";
        wxFile shDebugLogFile;

        // nodeInfo struct of the currently selected target load to be controlled
        SHnodeInfo  shCurrentLoadNodeInfo;
        wxString    shCurrentRoomName;  // Linux App extension to the NodeInfo structs
        wxString    shCurrentLoadName;  // Linux App extension to the NodeInfo structs

        wxSmartHomeServerFrame(wxWindow* parent,wxWindowID id = -1);
        virtual ~wxSmartHomeServerFrame();

        // Additional SmartHome functions
        void    SHguageDrawCurrentIntensity(void);
        void    shGUIupdateRoomName(uint16_t roomNum);
        void    shGUIupdateLoadName(uint16_t roomNum, uint8_t loadNum);

        uint16_t getNumRoomsFromStorage(void);
        uint16_t getNumLoadsInRoomFromStorage(uint16_t roomNum);


    private:

        uint16_t    lastRoomNum            = DEFAULT_ROOM_NUM;
        uint16_t    numRooms               = 0;
        uint16_t    currentRoomNum         = DEFAULT_ROOM_NUM;
        uint16_t    curNumLoadsInRoom      = 0;
        uint8_t     lastLoadNumInRoom      = DEFAULT_LOAD_NUM;
        uint8_t     currentLoadNumInRoom   = DEFAULT_LOAD_NUM;
        uint8_t     shCurrentIntensity     = LOAD_INTENSITY_FULL_OFF;      //selected load's current intensity level
        uint8_t     curSHcmdRepeats        = 0; // number of succesive presses/clicks of same GUI button

        uint8_t    *ptrThisNodeID = (uint8_t *)&shThisNodeID;
        uint8_t     shThisNodeType;         // 0=ctrl, 1=light, 2=fan, 3=server
        FILE       *FILEshEventsLog;


        //(*Handlers(wxSmartHomeServerFrame)
        void OnQuit(wxCommandEvent& event);
        void OnAbout(wxCommandEvent& event);
        void OnshBMPbtnRoomRightClick(wxCommandEvent& event);
        void OnshBMPbtnRoomLeftClick(wxCommandEvent& event);
        void OnshBMPbtnLoadRightClick(wxCommandEvent& event);
        void OnshBMPbtnLoadLeftClick(wxCommandEvent& event);
        void OnshBMPbtnIncIntClick(wxCommandEvent& event);
        void OnshBMPbtnFavIntClick(wxCommandEvent& event);
        void OnshBMPbtnDecIntClick(wxCommandEvent& event);
        void OnshBMPbtnOnClick(wxCommandEvent& event);
        void OnshBMPbtnOffClick(wxCommandEvent& event);
        //*)

        // Additional SmartHome functions
        void      SHinitServerNodeInfo(void);
        void      SHinitLoadNodeInfo(void);
        uint16_t  SHgetLoadNodeIDfromStorage(uint16_t roomNum, uint16_t loadNum);
        uint8_t   SHgetLoadNodeTypefromStorage(uint16_t roomNum, uint16_t loadNum);
        wxString  SHgetRoomNamefromStorage(uint16_t roomNum);
        wxString  SHgetLoadNamefromStorage(uint16_t roomNum, uint16_t loadNum);
        void     _changeRoom(uint8_t changeDirection);
        void      selectRoom(uint16_t roomNum);
        void     _changeLoad(uint8_t changeDirection);
        void      selectLoad(uint16_t loadNum);


        //(*Identifiers(wxSmartHomeServerFrame)
        static const long ID_TEXTCTRL_SH_EVT_LOG;
        static const long ID_GAUGE_SH_LD;
        static const long ID_BITMAPBUTTON_SH_UP;
        static const long ID_BITMAPBUTTON_SH_FAV;
        static const long ID_BITMAPBUTTON_SH_DWN;
        static const long ID_STATICTEXT1;
        static const long ID_STATICLINE1;
        static const long ID_BITMAPBUTTON_SH_ON;
        static const long ID_BITMAPBUTTON_SH_OFF;
        static const long ID_BITMAPBUTTON_SH_RM_LFT;
        static const long ID_BITMAPBUTTON_SH_LD_LFT;
        static const long ID_BITMAPBUTTON_SH_RM_RT;
        static const long ID_BITMAPBUTTON_SH_LD_RT;
        static const long ID_CHECKBOX_SH_HM1;
        static const long ID_CHECKBOX_SH_HM2;
        static const long ID_STATICTEXT_SH_RM_NAME;
        static const long ID_STATICTEXT_SH_LD_NAME;
        static const long ID_STATICBITMAP1;
        static const long ID_STATICBITMAP2;
        static const long ID_STATICBITMAP3;
        static const long ID_STATICBITMAP4;
        static const long ID_TEXTCTRL_SH_CURTIME; //ID_TEXTCTRL2;
        static const long ID_TEXTCTRL_SH_CURDATE;
        static const long ID_TEXTCTRL_SH_ROOMNAME;
        static const long ID_TEXTCTRL_SH_LOADNAME;
        static const long ID_PANEL1;
        static const long idMenuQuit;
        static const long idMenuAbout;
        static const long ID_STATUSBAR1;
        //*)

        //(*Declarations(wxSmartHomeServerFrame)
        wxBitmapButton* shBMPbtnLoadRight;
        wxCheckBox* shCheckBoxIsHome2;
        wxStatusBar* StatusBar1;
        wxBitmapButton* shBMPbuttonON;
        wxCheckBox* shCheckBoxIsHome1;
        wxTextCtrl* shTextCtrlRoomName;
        wxStaticText* StaticText1;
        wxBitmapButton* shBMPbtnRoomLeft;
        wxBitmapButton* shBMPbuttonFAV;
        wxBitmapButton* shBMPbtnRoomRight;
        wxBitmapButton* shBMPbtnLoadLeft;
        wxStaticLine* StaticLine1;
        wxPanel* shPanel1;
        wxBitmapButton* shBMPbuttonOFF;
        wxBitmapButton* shBMPbuttonDWN;
        wxStaticBitmap* StaticBitmap3;
        wxStaticBitmap* StaticBitmap1;
        wxTextCtrl* shTextCtrlLoadName;
        wxStaticBitmap* StaticBitmap4;
        wxBitmapButton* shBMPbuttonUP;
        wxStaticBitmap* StaticBitmap2;
        //*)



        DECLARE_EVENT_TABLE()
};

#endif // WXSMARTHOMESERVERMAIN_H
