/***************************************************************
 * Name:      wxSmartHomeServerApp.h
 * Purpose:   Defines Application Class
 * Author:    Bill Toner (wtoner1@jhu.edu)
 * Created:   2015-11-17
 * Copyright: Bill Toner ()
 * License:
 * Initially generated by wxSmith GUI builder tool
 **************************************************************/

#ifndef WXSMARTHOMESERVERAPP_H
#define WXSMARTHOMESERVERAPP_H

#include <wx/app.h>
#include <wx/file.h>

#include <stdint.h>


#define SH_SERV_APP_NAME "wxSmartHomeServer"

#include "wxSmartHomeServerMain.h"


class wxSmartHomeServerApp : public wxApp
{
    public:
        virtual bool OnInit();
        void OnIdle(wxIdleEvent &event);

    private:
        wxSmartHomeServerFrame* Frame;
        size_t shLogFileumLinesPrev = 0; // number of lines in the SmartHome Control Event log file from the last time we checked
        size_t shLogFileLengthPrev = 0; // number of lines in the SmartHome Control Event log file from the last time we checked
        wxString _shCurrentDateTime;
        wxString _shCurrentDay;
        wxString _shCurrentMonth;
        wxString _shCurrentDate;
        wxString _shCurrentYear;
        wxString _shCurrentFullDate;
        wxString _shCurrentTime;

        uint8_t SHupdateGUIlogText(const wxString& shLogFileName);
        uint8_t SHupdateGUItimeText(void);

        DECLARE_EVENT_TABLE()

};

#endif // WXSMARTHOMESERVERAPP_H
